### ISSUE TITLE
Aggregation factor of zero leads to an error in a `matrix` calculation (ncol too large or NA)

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/spatialEpisim#10]
```
Warning in matrix(data = 0, nrow = nrow(x = input_matrix), ncol = radius) :
  NAs introduced by coercion to integer range
Warning: Error in matrix: invalid 'ncol' value (too large or NA)
  1: runApp
```

**Comment by ashokkrish** [comment]
> ```
> Warning in matrix(data = 0, nrow = nrow(x = input_matrix), ncol = radius) :
>   NAs introduced by coercion to integer range
> Warning: Error in matrix: invalid 'ncol' value (too large or NA)
>   1: runApp
> ```

An aggregation factor of 0 should not even be an option. See if you can adjust the `rasterAgg` slider.

**Comment by bryce-carson** [comment]
> > ```
> > Warning in matrix(data = 0, nrow = nrow(x = input_matrix), ncol = radius) :
> >   NAs introduced by coercion to integer range
> > Warning: Error in matrix: invalid 'ncol' value (too large or NA)
> >   1: runApp
> > ```
> 
> An aggregation factor of 0 should not even be an option. See if you can adjust the `rasterAgg` slider.

Indeed. Thanks. Done!
