### ISSUE TITLE
Display simulation progress rather than indefinite waiter

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/spatialEpisim#13]
The waiter currently used is an "indefinite" one, while the progress of the simulation is known because it prints the current time of the simulation every "tick."

**Comment by ashokkrish** [comment]
> The waiter currently used is an "indefinite" one, while the progress of the simulation is known because it prints the current time of the simulation every "tick."

This would be a valuable enhancement especially when simulations are running and the user gets an idea as to how much longer it might take to finish running.

**Comment by bryce-carson** [comment]
For this I am providing the SVEIRD function with a parameter which allows the Shiny application to provide an optional callback function, which is what will be used by the "waitress" from the _waiter_ package.
