### ISSUE TITLE
Reset default selectedCountry

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/spatialEpisim#16]
Right now the DRC and two northeastern provinces are the selected by default.

<img width="384" alt="image" src="https://github.com/ashokkrish/spatialEpisim/assets/410949/1252b37d-5497-415b-b12f-ec3acce55264">

I would like to reset this to no country selected. My upcoming presentations predominantly focus on Greece and Italy so I would like no country selected on initial run.

**Comment by bryce-carson** [comment]
Can do!
