### ISSUE TITLE
Should the first day's results be included in summary columns?

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/spatialEpisim#17]
See the following table...

||Date|N|S|V|E|I|R|D|newV|newE|newI|newR|newD|cumE|cumI|Alpha|Beta|Gamma|Sigma|Delta|Radius|Lambda|Model|DA|
|--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |
|1|2024-06-11|473,602|465,682|6,000|1,200|600|60|60|69|836|11|39|1|1,200|600|0.00015|0.055|0.009|0.065|0.0015|3|15|SVEIRD|0|
|2|2024-06-12|465,682|456,857|6,069|2,025|571|99|61|69|761|18|37|1|2,036|611|0.00015|0.055|0.009|0.065|0.0015|3|15|SVEIRD|0|
|3|2024-06-13|465,682|456,028|6,137|2,768|551|136|62|68|707|25|35|1|2,797|629|0.00015|0.055|0.009|0.065|0.0015|3|15|SVEIRD|0|
|4|2024-06-14|465,682|455,253|6,206|3,450|540|171|63|68|674|31|34|1|3,504|654|0.00015|0.055|0.009|0.065|0.0015|3|15|SVEIRD|0|
|5|2024-06-15|465,682|454,510|6,274|4,093|536|205|63|68|656|37|32|1|4,178|685|0.00015|0.055|0.009|0.065|0.0015|3|15|SVEIRD|0|
|6|2024-06-16|465,682|453,786|6,342|4,712|540|237|64|68|649|42|31|1|4,834|722|0.00015|0.055|0.009|0.065|0.0015|3|15|SVEIRD|0|
|7|2024-06-17|465,682|453,069|6,410|5,319|551|268|65|68|652|47|31|1|5,483|764|0.00015|0.055|0.009|0.065|0.0015|3|15|SVEIRD|0|
|8|2024-06-18|465,682|452,350|6,478|5,923|567|299|66|68|661|53|31|1|6,134|811|0.00015|0.055|0.009|0.065|0.0015|3|15|SVEIRD|0|
|9|2024-06-19|465,682|451,621|6,546|6,531|588|330|66|68|677|59|35|1|6,795|864|0.00015|0.055|0.009|0.065|0.0015|3|15|SVEIRD|0|
|10|2024-06-20|465,682|450,877|6,614|7,149|611|365|67|68|693|64|39|1|7,472|923|0.00015|0.055|0.009|0.065|0.0015|3|15|SVEIRD|0|

@ashokkrish, personally, I'd expect the number of infected at _the end of the first day_ to be $I = 600_I + 11_I - 39_R - 1_D = 571_I$, since there are eleven new infections and thirty-seven people recovered. The next day, I'd expect the number of active infections to begin at this reduced number, but also include the new infections at the end of this second reporting day, and the number of people that recovered during this day as well, ie $I = 572_I + 18_I - 37_R - 1_D = 551_I$.

What should it be? It seems a little awkward, at least. It might be incorrect. Perhaps a caption for the table should specify that the value in $I$ is actually the initial number of infected, the number at the beginning of that day, not the end.

**Comment by bryce-carson** [comment]
@ashokkrish, may I have your input on this question?

**Comment by ashokkrish** [comment]
> @ashokkrish, may I have your input on this question?

Typically Day 1 is the day simulation begins with the user input. Day 2 is what is after 1 full day. I would leave Day 1 as is because sometimes we might want to see how many new cases after one day so Day 1 pis a reference point. I hope this make sense.

**Comment by bryce-carson** [comment]
Yes, very helpful.
