### ISSUE TITLE
Validate the entries of the uploaded seed data

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/spatialEpisim#25]
When the user uploads the seed data and clicks 

<img width="110" alt="image" src="https://github.com/ashokkrish/spatialEpisim/assets/410949/f012b902-4d36-47ba-8dcb-cf45251866d8">

The first thing we need to do is validate the entries of the seed data. Are columns for V, E, I, R, D filled with with numbers? If an invalid character appears then prompt an error message on the mainPanel. If the entries are left blank replace them by zero.

Next, check if all the Lat-Lon pairs are within the spatial domain of the selectedCountry. For example, when the selectedCountry is Italy but the user uploads a seed data for Greece then it makes no sense. In this case we need to give an appropriate warning on the mainPanel().

**Comment by bryce-carson** [comment]
This is related to #5.

**Comment by bryce-carson** [comment]
@kle6951 and @Toby-exe, please write a few lines which check that all the observations in the uploaded seed data are non-negative, and replace any missing values with zeros. Perform the work in the stable branch, or a feature branch in which you're doing the same work for #5. Then we can merge the solution to #5 and this (#25) in one fell swoop.

**Comment by bryce-carson** [comment]
@Toby-exe Please add this issue to the Monthly roadmap in the newly created project; add it to the roadmap when you started working on this issue, or when you think you can begin working on it. Then, when hovering to the right of the rectangle in the roadmap a vertical line will appear allowing you to drag and extend the project to the date you expect to be able to complete the project and resolve the issue.

**Comment by Toby-exe** [comment]
@ashokkrish please see the latest commit for progress on this issue.

**Comment by ashokkrish** [comment]
> @ashokkrish please see the latest commit for progress on this issue.

I will pull the code now and test it out. Thank you all for working tirelessly on this project.

**Comment by bryce-carson** [comment]
> @bryce-carson I tried uploading Italy seed data for the Democratic Republic of Congo and the app crashed with this error:
> 
> **[1] "Dem. Rep. Congo" Warning: Error in ne_states: No such country (Dem. Rep. Congo) in the data 1: runApp**

It looks like the `ne_states` function is receiving an abbreviation of the name of country. That's definitely wrong, as any country name (in English) should be written as found in `countrycode::codelist$country.name.en`.

@Toby-exe, can you resolve this error in your new code?

**Comment by bryce-carson** [comment]
> @bryce-carson I tried uploading Italy seed data for the Democratic Republic of Congo and the app crashed with this error:
> 
> **[1] "Dem. Rep. Congo" Warning: Error in ne_states: No such country (Dem. Rep. Congo) in the data 1: runApp**

Ashok, we've already encountered this error. I'm going to close the duplicate in #41.

@Toby-exe, you need to address this issue in stable, please, since that's where you integrated the code.

**Comment by Toby-exe** [comment]
> > @bryce-carson I tried uploading Italy seed data for the Democratic Republic of Congo and the app crashed with this error:
> > **[1] "Dem. Rep. Congo" Warning: Error in ne_states: No such country (Dem. Rep. Congo) in the data 1: runApp**
> 
> @ashokkrish Ashok, we've already encountered this error. I'm going to close the duplicate in #41.
> 
> @Toby-exe, you need to address this issue in stable, please, since that's where you integrated the code.

@ashokkrish This has now been fixed, please try latest commit.

**Comment by bryce-carson** [comment]
Looks good!

**Comment by Toby-exe** [comment]
I believe 321ef2b0b465a81f3d265d1cb5f29e1cad400939 solves this issue
