### ISSUE TITLE
SEI compartment checkboxes are selectable (user is able to deselect them)

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/spatialEpisim#30]
The S, E, and I compartment selectors are not supposed to be enabled at the moment. They are supposed to be disabled, each with a value of `1` so that they are always on and cannot be turned off. Furthermore, the visual style of the application as it is (with MRU-style colours) makes it difficult to see the combo-button contents compared to a default bootstrap CSS.

**Comment by bryce-carson** [comment]
Compare the appearance of the boxes when the MRU-styled CSS is used, versus default bootstrap styling.

# MRU-style
![Screenshot 2024-07-15 at 22-41-53 spatialEpisim](https://github.com/user-attachments/assets/2fc4ae69-5ef1-46ac-8aa5-16941ff4ecbf)

# Bootstrap default
![Screenshot 2024-07-15 at 23-15-46 spatialEpisim](https://github.com/user-attachments/assets/f111d7da-1d13-462c-8538-f1dc6dc36156)

**Comment by ashokkrish** [comment]
I would like the MRU-style please.

**Comment by bryce-carson** [comment]
> I would like the MRU-style please.

Sure. The current MRU-style CSS needs some work, in my opinion, but an MRU colour scheme would be pleasant to have in the end. I'll open an issue to track that, because there are a lot of small points where things were overriden at too high a level and visual detail is lost, like the difference in the background colour of the combined checkbox group between the selected and unselected buttons/checkboxes.
