### ISSUE TITLE
WorldPop data should have a citation

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/spatialEpisim#34]
See the section **Recommended citation** on the webpage for [some of the data we use](https://hub.worldpop.org/geodata/summary?id=35824).

**Comment by ashokkrish** [comment]
Doesn't it say we are "**free to share**"?

<img width="805" alt="image" src="https://github.com/user-attachments/assets/e4cc5256-5143-43ac-bcf5-0c078e49a26c">

**Comment by bryce-carson** [comment]
> Doesn't it say we are "**free to share**"?
> <img alt="image" width="805" src="https://private-user-images.githubusercontent.com/410949/349428553-e4cc5256-5143-43ac-bcf5-0c078e49a26c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDYyMDQsIm5iZiI6MTcyMTIwNTkwNCwicGF0aCI6Ii80MTA5NDkvMzQ5NDI4NTUzLWU0Y2M1MjU2LTUxNDMtNDNhYy1iY2Y1LTBjMDc4ZTQ5YTI2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QwODQ1MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzIyMmExZGIyZWQzZDJjMDc2NmY5OWM4MDdmYjcyOTlmMjk2NmUxYmU4YzhiYWQ1MDI3M2Y5MGNiYjRlNTA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EZETjAPLkYMkhIDTInP-8wRQtEVGuT9ejKnwfEJu5V8">

Yes, but the terms of the Creative Commons Attribution 4.0 International License are _summarized_ here. We need to give attribution in the place where we use the data.

**Comment by bryce-carson** [comment]
> Doesn't it say we are "**free to share**"?
> 
> > WorldPop datasets are available under the Creative Commons Attribution 4.0 International License. This means that you are free to share (copy and redistribute the material in any medium or format) and adapt (remix, transform, and build upon the material) for any purpose, even commercially, provided attribution is included (appropriate credit and a link to the licence).

Don't confuse this licensing issue with #35. That one is separate.

**Comment by bryce-carson** [comment]
> Sorry my bad!

No worries!

**Comment by bryce-carson** [comment]
@kle6951, you can work on this.

Do some reading from various writers in the R community and learn of a nice way to thank all the authors of the packages we use in our Shiny app.

It'd be appropriate to include a collapsible list of used packages in the authors tab, I think. You can work on it in stable.

**Comment by kle6951** [comment]
@ashokkrish @bryce-carson Please take a look at the citation in the authors tab panel and please let me know if it needs more improvement or adjustment. Thank you!
<img width="1440" alt="Screenshot 2024-07-31 at 8 30 59 PM" src="https://github.com/user-attachments/assets/44fc3429-6746-4ea5-b946-b9148a3feb8d">

**Comment by bryce-carson** [comment]
That looks okay, @kle6951! Are you using the `citation()` function and other facilities like I suggested, or writing that out manually?

**Comment by kle6951** [comment]
> That looks okay, @kle6951! Are you using the `citation()` function and other facilities like I suggested, or writing that out manually?

For all the R packages, I used the function `packageDescription()` to retrieve the package description, which I found online and it's very convenient to use. For the World Pop data, since I followed the suggested citation on their webpage, I just manually wrote the citation only for the World Pop data.

**Comment by bryce-carson** [comment]
> > That looks okay, @kle6951! Are you using the `citation()` function and other facilities like I suggested, or writing that out manually?
> 
> For all the R packages, I used the function `packageDescription()` to retrieve the package description, which I found online and it's very convenient to use. For the World Pop data, since I followed the suggested citation on their webpage, I just manually wrote the citation only for the World Pop data.

Okay; there are some facilities built-in to the R ecosystem to assist with citations. Please read about these and utilize them to save yourself time and ensure accuracy.

**Comment by kle6951** [comment]
> > > That looks okay, @kle6951! Are you using the `citation()` function and other facilities like I suggested, or writing that out manually?
> > 
> > 
> > For all the R packages, I used the function `packageDescription()` to retrieve the package description, which I found online and it's very convenient to use. For the World Pop data, since I followed the suggested citation on their webpage, I just manually wrote the citation only for the World Pop data.
> 
> Okay; there are some facilities built-in to the R ecosystem to assist with citations. Please read about these and utilize them to save yourself time and ensure accuracy.

Sounds good. I will take a look at it and make change accordingly
