### ISSUE TITLE
Authors tab

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/spatialEpisim#40]
<img width="237" alt="image" src="https://github.com/user-attachments/assets/a4e8c867-8292-4a39-a87a-9d7ebc1f2ed6">

Hyperlink the spatialEpisim GitHub, right now it is redirecting to the episim GitHub.

**Comment by kle6951** [comment]
I’ll fix this!

**Comment by ashokkrish** [comment]
Change the header **Supervisor** to **Principal investigator**
