### ISSUE TITLE
sidiag not found

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/spatialEpisim#49]
We hot-fixed this during the meeting today (2024-08-27); it needs to be permanently fixed.

**Comment by ashokkrish** [comment]
@bryce-carson and @Toby-exe Control over to you to run a simple Bayesian Data Assimilation (BDA) simulation without any errors.

Along the way fix the H matrix creation with the bug noticed by Bryce. The Q matrix can be generated using the old code for now. The main branch should be able to run BDA without errors so I can deploy it to ShinyApps.io.

**Comment by bryce-carson** [comment]
> @bryce-carson and @Toby-exe Control over to you to run a simple Bayesian Data Assimilation (BDA) simulation without any errors.
> 
> Along the way fix the H matrix creation with the bug noticed by Bryce. The Q matrix can be generated using the old code for now. The main branch should be able to run BDA without errors so I can deploy it to ShinyApps.io.

Thank you for the direction, it always helps.

**Comment by Toby-exe** [comment]
issue re-opened due to another typo. Fixed in in coming commit
