### ISSUE TITLE
Decide whether to keep prepending "the" to particular country names

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/spatialEpisim#52]
Various sources in grammar and law indicate that it is debatable whether any country being named should be introduced with the word "the". Examples where it is common include "the United Kingdom," but this is a introductory statement, and not part of the country name. Some countries are named for geographical entities like notable rivers or forests, so were Brazil to fall apart as a nation and reform into smaller nations we might see things like "the Republic of the Amazon," or the "the Communist People's Democracy of the Amazon". Introducing words like "the" are helpful in prose, but I'm unsure of the real "utility" of this vector, other than automatically modifying a very small part of the plotting functionality of the application.

Given we'll be integrating [KrishnamurthyLab/react-chart-editoR](https://github.com/KrishnamurthyLab/react-chart-editoR) into the application, I don't think the extra logic is worth retaining in the application. It is trivial logic, however, so it's fine either way.

https://github.com/ashokkrish/spatialEpisim/blob/ac822a76f775c498eec1ed01ca715c8040d63cf3/global.R#L49-L53

**Comment by bryce-carson** [comment]
### Sources
- [Tomas Schild's opinion, written on Quora](https://qr.ae/p2KHSi)
- [John Gordon's opinion, also written on Quora](https://qr.ae/p2KHcS)
- [Kathryn E. Graber, Associate Professor of Anthropology and Central Eurasian Studies, Indiana University, article on _The Conversation_](https://theconversation.com/its-ukraine-not-the-ukraine-heres-why-178748)

**Comment by bryce-carson** [comment]
In summary, it might be better to simply let the end user decide whether to include grammatical articles like "the" or "a" in when referring to a country's name in a plot title or subtitle or legend when they're editing it with the react-chart-editor component, rather than try to serve everyone amicably and equally and reduce their workload.

**Comment by bryce-carson** [comment]
https://en.wikipedia.org/wiki/ISO_3166-1

I think there's simply too many troubles involved in handling _any_ country specially; we can just use the names of countries as listed in _countrycode_'s English vector of country names and all other concerns can be left up to the user of the package.

**Comment by ashokkrish** [comment]
Sorry about the late response. The only countries we are running simulations at the moment are for the DRC, the Czech Republic, South Korea, Nigeria, Italy and Greece. Therefore I would treat this as low priority right now and not worry about prepending "the" to particular country names. You can close this issue.
