### ISSUE TITLE
Switch spatialEpisim to have a top ribbon to be within the Krishnamurthy Lab 

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/spatialEpisim#56]
@bryce-carson 

In the [episim app](https://ashokkrish.shinyapps.io/episim/) we have

<img width="638" alt="image" src="https://github.com/user-attachments/assets/72af8b04-e6cf-4148-8fa6-77dd462f9ed2">
 

The same way for the [spatialEpisim app](https://ashokkrish.shinyapps.io/spatialepisim/) I want this 
 
<img width="941" alt="image" src="https://github.com/user-attachments/assets/cdd1c4a9-c675-45e8-a834-4cc145ab59bf">

to be replaced with 

**The Krishnamurthy Lab Spatio-Temporal Epidemic Modelling app**

Can you do this switch on the main branch by the end of the week so I can deploy it to the ShinyApps.io server?

**Comment by ashokkrish** [comment]
@bryce-carson Will you be able to get this issue closed in the next 1 or 2 days?

**Comment by bryce-carson** [comment]
> @bryce-carson Will you be able to get this issue closed in the next 1 or 2 days?

I believe so. It's a small item.

**Comment by bryce-carson** [comment]
https://github.com/ashokkrish/episim/blob/aff27354812943b25f1d41f31f7bf3a764804291/ui.R#L367-L375

I'm going to try inserting this into the UI and if it looks alright I'll push it. It might not integrate well because the UI in spatialEpisim's main branch is constructed differently than Episim's.

**Comment by bryce-carson** [comment]
@ashokkrish, the change is accomplished; the UI overall is still in a bad state but not worth reconstructing at this late stage when the UI is already being overhauled in the refactored branch.

**Comment by ashokkrish** [comment]
@bryce-carson Thanks for the update. I didn't know the UI is being overhauled in the refactored branch. I was under the impression that the current UI is quite solid and you are basically going to connect package with the existing UI. I'd love to see the new UI preview if available.

**Comment by bryce-carson** [comment]
> @bryce-carson Thanks for the update. I didn't know the UI is being overhauled in the refactored branch. I was under the impression that the current UI is quite solid and you are basically going to connect package with the existing UI. I'd love to see the new UI preview if available.

The UI is staying the same for the most part. I want to play with a stepped wizard, but that's just an idea and a lot of trouble to implement right now.

The UI is staying the same in effect and appearance, but just rewritten so it is clean and organized.
